name: Build all Docker images

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build_images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type:
          - master
          - worker
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.type }}/Dockerfile
          push: true
          tags: |
            gnuoctave/buildbot:latest-${{ matrix.type }}
            ghcr.io/gnu-octave/buildbot:latest-${{ matrix.type }}
