name: "freshly brewed Octave"

on:
  # push:
  workflow_dispatch:
  schedule:
    # Run job every day at 16:30 UTC
    - cron: '30 16 * * *'

jobs:
  check:
    name: Windows test suite

    runs-on: windows-latest

    defaults:
      run:
        # Use pre-installed MSYS2 as default shell
        shell: C:/msys64/usr/bin/bash.exe --login -eo pipefail "{0}"

    strategy:
      fail-fast: false
      matrix:
        target: [w64-default, w64, w64-64, w32]
        include:
          - target: w64-default
            file-suffix: default-w64
            folder-suffix: w64
            mingw-prefix: mingw64
          - target: w64
            file-suffix: w64
            folder-suffix: w64
            mingw-prefix: mingw64
          - target: w64-64
            file-suffix: w64-64
            folder-suffix: w64-64
            mingw-prefix: mingw64
          - target: w32
            file-suffix: w32
            folder-suffix: w32
            mingw-prefix: mingw32

    env:
      MSYSTEM: MSYS
      CHERE_INVOKING: 1

    steps:
      - name: prepare cache
        # Create human readable timestamp
        id: cache_timestamp
        run: |
          echo "::set-output name=TIMESTAMP::$(date +"%Y-%m-%d_%H-%M-%S")"

      - name: setup cache
        id: setup-cache
        # uses: actions/cache@v2
        # The original action doesn't upload on error. Use this fork instead.
        uses: pat-s/always-upload-cache@v2
        with:
          path: oldid/${{ matrix.target }}
          key: oldid:${{ matrix.target }}:${{ steps.cache_timestamp.outputs.timestamp }}:${{ github.sha }}
          restore-keys: oldid:${{ matrix.target }}
 
      - name: check build id
        id: check-id
        env:
          TARGET: ${{ matrix.target }}
        run: |
          BUILDID=$(curl -s "https://buildbot.octave.space/api/v2/builders/octave/builds?state_string__eq=build%20successful&order=-started_at&limit=1" | grep "number" | grep -o "[0-9]*")
          echo "::set-output name=BUILDID::${BUILDID}"
          echo buildid: "${BUILDID}"
          mkdir -p oldid/${TARGET}
          test -f oldid/${TARGET}/id && OLDBUILDID=$(cat oldid/${TARGET}/id)
          echo "::set-output name=OLDBUILDID::${OLDBUILDID}"
          echo oldbuildid: "${OLDBUILDID}"

      - name: download build
        id: download
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          BUILDID: ${{ steps.check-id.outputs.buildid }}
          FILE_SUFFIX: ${{ matrix.file-suffix }}
        run: |
          wget --no-check-certificate -O index.html "https://www.octave.space/data/stable/${BUILDID}/" || true
          FILE7Z=$(grep -r "\-${FILE_SUFFIX}.7z" index.html | grep -o -P -m 1 "octave-[0-9\-]*-${FILE_SUFFIX}.7z" | head -n1 -)
          wget --no-check-certificate -O octave-${FILE_SUFFIX}.7z "https://www.octave.space/data/stable/${BUILDID}/${FILE7Z}"
          echo "::set-output name=FILE7Z::${FILE7Z}"

      - name: unpack
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        shell: cmd
        env:
          FILE_SUFFIX: ${{ matrix.file-suffix }}
        run: 7z.exe x -y octave-%FILE_SUFFIX%.7z

      - name: prepare
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
          FOLDER_SUFFIX: ${{ matrix.folder-suffix }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")${FOLDER_SUFFIX}
          ./post-install.bat

      - name: show hg ids
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
          FOLDER_SUFFIX: ${{ matrix.folder-suffix }}
          MY_MINGW_PREFIX: ${{ matrix.mingw-prefix }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")${FOLDER_SUFFIX}
          echo MXE Octave hg id:
          cat HG-ID
          echo Octave hg id:
          ./${MY_MINGW_PREFIX}/bin/octave.bat --no-init-file --silent --no-history --eval "fprintf ('%s', version ('-hgid'))"

      - name: run test suite
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
          FOLDER_SUFFIX: ${{ matrix.folder-suffix }}
          MY_MINGW_PREFIX: ${{ matrix.mingw-prefix }}
        # Write access to the /tmp folder that MSYS2 uses by default seems to be restricted.
        run: |
          export TMP="$RUNNER_TEMP"
          export TEMP="$RUNNER_TEMP"
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")${FOLDER_SUFFIX}
          ./${MY_MINGW_PREFIX}/bin/octave.bat --no-init-file --silent --no-history --eval __run_test_suite__ | tee ./test-suite.log

      - name: display log
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
          FOLDER_SUFFIX: ${{ matrix.folder-suffix }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")${FOLDER_SUFFIX}
          cat ./fntests.log

      - name: save old build id
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          BUILDID: ${{ steps.check-id.outputs.buildid }}
          TARGET: ${{ matrix.target }}
        run: echo $BUILDID > oldid/${TARGET}/id

      - name: analyze test suite result
        if: steps.check-id.outputs.buildid != steps.check-id.outputs.oldbuildid
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
          FOLDER_SUFFIX: ${{ matrix.folder-suffix }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")${FOLDER_SUFFIX}
          [ -n "$(grep -e "FAIL\s*0" ./test-suite.log)" ] || exit 1
          [ -z "$(grep -e "REGRESSION" ./test-suite.log)" ] || exit 1
