name: "windows"

on:
  # push:
  workflow_dispatch:
  schedule:
    # Run job every Monday and Thursday at 16:30 UTC
    - cron: '30 16 * * 1,4'

jobs:
  analyze:
    name: Windows test suite
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    strategy:
      fail-fast: false

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          # install: git mingw-w64-x86_64-toolchain

      - name: download build
        id: download
        run: |
          BUILDID=$(curl -s "https://buildbot.octave.space/api/v2/builders/octave/builds?state_string__eq=build%20successful&order=-started_at&limit=1" | grep "number" | grep -o "[0-9]*")
          wget --no-check-certificate -O index.html "https://www.octave.space/data/stable/${BUILDID}/"
          FILE7Z=$(grep -r "\-default-w64.7z" index.html | grep -o -P -m 1 "octave-[0-9\-]*-default-w64.7z" | head -n1 -)
          wget --no-check-certificate -O octave-default-w64.7z "https://www.octave.space/data/stable/${BUILDID}/${FILE7Z}"
          echo "::set-output name=FILE7Z::${FILE7Z}"

      - name: unpack
        shell: pwsh
        run: 7z.exe x -y octave-default-w64.7z

      - name: prepare
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")w64
          ./post-install.bat

      - name: run test suite
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")w64
          ./mingw64/bin/octave.bat --no-init-file --silent --no-history --eval __run_test_suite__

      - name: display log
        env:
          FILE7Z: ${{ steps.download.outputs.file7z }}
        run: |
          cd $(echo ${FILE7Z} | grep -o -P "octave-[0-9\-]*")w64
          cat ./fntests.log
